#Requires -Version 7.0

<#
.SYNOPSIS
    Post-provision hook: patches redirect URI, assigns RBAC, and writes local config.
.DESCRIPTION
    Runs after azd provision. Uses Bicep outputs (now in azd env) to:
    1. Add the production SWA URL as a SPA redirect URI on the app registration
    2. Assign Storage Blob Data Contributor to the Function App managed identity
    3. Write portal/.env with correct values for local development
#>

$ErrorActionPreference = 'Stop'

function Get-AzdEnv([string]$Key) {
    $val = azd env get-value $Key 2>$null
    if ($LASTEXITCODE -ne 0) { return $null }
    return $val
}

# ---------------------------------------------------------------------------
# Read outputs from azd environment
# ---------------------------------------------------------------------------

$clientId       = Get-AzdEnv 'AZURE_CLIENT_ID'
$tenantId       = Get-AzdEnv 'AZURE_TENANT_ID'
$swaUrl         = Get-AzdEnv 'AZURE_STATIC_WEB_APP_URL'
$storageId      = Get-AzdEnv 'AZURE_STORAGE_ACCOUNT_ID'
$functionAppName = Get-AzdEnv 'AZURE_FUNCTION_APP_NAME'
$resourceGroup  = Get-AzdEnv 'AZURE_RESOURCE_GROUP'

if (-not $swaUrl) { throw "AZURE_STATIC_WEB_APP_URL not found in azd env — was provision successful?" }

Write-Host "`n=== W365 Swap — Post-Provision ===" -ForegroundColor Cyan

# ---------------------------------------------------------------------------
# 1. Patch SPA redirect URIs with production SWA URL
# ---------------------------------------------------------------------------

Write-Host "Updating SPA redirect URIs with production URL..." -ForegroundColor Cyan

$appManifest = az ad app show --id $clientId --output json | ConvertFrom-Json
$currentUris = @($appManifest.spa.redirectUris)

if ($swaUrl -notin $currentUris) {
    $updatedUris = @($currentUris + $swaUrl) | Select-Object -Unique

    $spaConfig = @{
        redirectUris = $updatedUris
    } | ConvertTo-Json -Compress

    az ad app update --id $clientId --set "spa=$spaConfig" --output none
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Added redirect URI: $swaUrl" -ForegroundColor Green
    } else {
        Write-Warning "Failed to update redirect URI — add '$swaUrl' manually in Entra ID."
    }
} else {
    Write-Host "Redirect URI already present." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# 2. Assign Storage Blob Data Contributor to Function App identity
# ---------------------------------------------------------------------------

Write-Host "Assigning Storage Blob Data Contributor to Function App..." -ForegroundColor Cyan

# Get Function App managed identity principal ID
$funcApp = az functionapp identity show --name $functionAppName --resource-group $resourceGroup --output json 2>$null | ConvertFrom-Json
if ($funcApp -and $funcApp.principalId) {
    $principalId = $funcApp.principalId

    # Storage Blob Data Contributor role ID
    $roleDef = 'ba92f5b4-2d11-453d-a403-e96b0029c9fe'

    $existing = az role assignment list `
        --assignee $principalId `
        --role $roleDef `
        --scope $storageId `
        --query "[0]" 2>$null | ConvertFrom-Json

    if (-not $existing) {
        az role assignment create `
            --assignee-object-id $principalId `
            --assignee-principal-type ServicePrincipal `
            --role $roleDef `
            --scope $storageId `
            --output none
        if ($LASTEXITCODE -eq 0) {
            Write-Host "RBAC assigned: Storage Blob Data Contributor" -ForegroundColor Green
        } else {
            Write-Warning "Failed to assign storage RBAC — assign manually."
        }
    } else {
        Write-Host "RBAC assignment already exists." -ForegroundColor Green
    }
} else {
    Write-Warning "Could not retrieve Function App identity — assign storage RBAC manually."
}

# ---------------------------------------------------------------------------
# 3. Write portal .env for local development
# ---------------------------------------------------------------------------

Write-Host "Writing portal/.env for local development..." -ForegroundColor Cyan

$portalEnvPath = Join-Path $PSScriptRoot '..' 'portal' '.env'
$portalEnvContent = @"
# Auto-generated by azd post-provision hook — $(Get-Date -Format 'yyyy-MM-dd HH:mm')
NEXT_PUBLIC_AZURE_TENANT_ID="$tenantId"
NEXT_PUBLIC_AZURE_CLIENT_ID="$clientId"
NEXT_PUBLIC_API_BASE_URL="/api"

# API Backend (Azure Functions local settings)
AZURE_TENANT_ID="$tenantId"
AZURE_CLIENT_ID="$clientId"
AZURE_CLIENT_SECRET="$(Get-AzdEnv 'AZURE_CLIENT_SECRET')"
"@
$portalEnvContent | Set-Content $portalEnvPath -Encoding utf8
Write-Host "Written: portal/.env" -ForegroundColor Green

# Also write portal/api/local.settings.json for local func development
$localSettingsPath = Join-Path $PSScriptRoot '..' 'portal' 'api' 'local.settings.json'
$localSettings = @{
    IsEncrypted = $false
    Values = @{
        AzureWebJobsStorage        = ''
        FUNCTIONS_WORKER_RUNTIME   = 'node'
        FUNCTIONS_EXTENSION_VERSION = '~4'
        AZURE_TENANT_ID            = $tenantId
        AZURE_CLIENT_ID            = $clientId
        AZURE_CLIENT_SECRET        = (Get-AzdEnv 'AZURE_CLIENT_SECRET')
        STORAGE_ACCOUNT_ID         = $storageId
    }
} | ConvertTo-Json -Depth 3
$localSettings | Set-Content $localSettingsPath -Encoding utf8
Write-Host "Written: portal/api/local.settings.json" -ForegroundColor Green

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

Write-Host "`n=== Post-provision complete ===" -ForegroundColor Cyan
Write-Host "Portal URL:    $swaUrl"
Write-Host "Function App:  $(Get-AzdEnv 'AZURE_FUNCTION_APP_URL')"
Write-Host "Storage:       $(Get-AzdEnv 'AZURE_STORAGE_ACCOUNT_NAME')"
Write-Host "Key Vault:     $(Get-AzdEnv 'AZURE_KEY_VAULT_NAME')"
Write-Host ""
Write-Host "Local dev files written:" -ForegroundColor DarkGray
Write-Host "  portal/.env"
Write-Host "  portal/api/local.settings.json"
Write-Host ""
