#Requires -Version 7.0

<#
.SYNOPSIS
    Post-provision hook: patches redirect URIs and writes local config.
.DESCRIPTION
    Runs after azd provision. Uses Bicep outputs (now in azd env) to:
    1. Add the production SWA URL (and any AZURE_EXTRA_REDIRECT_URIS) as SPA
       redirect URIs on the app registration, merging with whatever is already
       configured so manually-added entries (e.g. custom domains) survive.
    2. Write portal/.env, portal/web/.env, and portal/api/local.settings.json
       for local development.
#>

$ErrorActionPreference = 'Stop'

function Get-AzdEnv([string]$Key) {
    $val = azd env get-value $Key 2>$null
    if ($LASTEXITCODE -ne 0) { return $null }
    return $val
}

# ---------------------------------------------------------------------------
# Read outputs from azd environment
# ---------------------------------------------------------------------------

$clientId       = Get-AzdEnv 'AZURE_CLIENT_ID'
$tenantId       = Get-AzdEnv 'AZURE_TENANT_ID'
$swaUrl         = Get-AzdEnv 'AZURE_STATIC_WEB_APP_URL'
$functionAppName = Get-AzdEnv 'AZURE_FUNCTION_APP_NAME'
$resourceGroup  = Get-AzdEnv 'AZURE_RESOURCE_GROUP'

if (-not $swaUrl) { throw "AZURE_STATIC_WEB_APP_URL not found in azd env — was provision successful?" }

Write-Host "`n=== Mosaic — Post-Provision ===" -ForegroundColor Cyan

# ---------------------------------------------------------------------------
# 1. Patch SPA redirect URIs with production SWA URL + any extras
# ---------------------------------------------------------------------------

Write-Host "Updating SPA redirect URIs..." -ForegroundColor Cyan

$appManifest = az ad app show --id $clientId --output json | ConvertFrom-Json
$currentUris = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase
)
foreach ($u in @($appManifest.spa.redirectUris)) {
    if ($u) { [void]$currentUris.Add($u) }
}

$desired = [System.Collections.Generic.List[string]]::new()
if ($swaUrl) { [void]$desired.Add($swaUrl) }

$extraUris = Get-AzdEnv 'AZURE_EXTRA_REDIRECT_URIS'
if ($extraUris) {
    foreach ($u in ($extraUris -split '[;,]')) {
        $u = $u.Trim()
        if ($u) { [void]$desired.Add($u) }
    }
}

$missing = $desired | Where-Object { -not $currentUris.Contains($_) }

if ($missing) {
    foreach ($u in $missing) { [void]$currentUris.Add($u) }
    $spaBody = @{
        spa = @{
            redirectUris = @($currentUris)
        }
    } | ConvertTo-Json -Depth 3

    $tempFile = [System.IO.Path]::GetTempFileName()
    $spaBody | Set-Content $tempFile -Encoding utf8
    az rest --method PATCH --url "https://graph.microsoft.com/v1.0/applications/$($appManifest.id)" --body "@$tempFile" --headers "Content-Type=application/json" --output none
    $patchResult = $LASTEXITCODE
    Remove-Item $tempFile -ErrorAction SilentlyContinue
    if ($patchResult -eq 0) {
        Write-Host "Added redirect URI(s): $($missing -join ', ')" -ForegroundColor Green
    } else {
        Write-Warning "Failed to update redirect URIs — add the following manually in Entra ID: $($missing -join ', ')"
    }
} else {
    Write-Host "Redirect URIs already up to date." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# 2. Write portal .env for local development
# ---------------------------------------------------------------------------

Write-Host "Writing portal/.env for local development..." -ForegroundColor Cyan

$portalEnvPath = Join-Path $PSScriptRoot '..' 'portal' '.env'
$portalEnvContent = @"
# Auto-generated by azd post-provision hook — $(Get-Date -Format 'yyyy-MM-dd HH:mm')
NEXT_PUBLIC_AZURE_TENANT_ID="$tenantId"
NEXT_PUBLIC_AZURE_CLIENT_ID="$clientId"
NEXT_PUBLIC_API_BASE_URL="/api"

# API Backend (Azure Functions local settings)
AZURE_TENANT_ID="$tenantId"
AZURE_CLIENT_ID="$clientId"
AZURE_CLIENT_SECRET="$(Get-AzdEnv 'AZURE_CLIENT_SECRET')"
"@
$portalEnvContent | Set-Content $portalEnvPath -Encoding utf8
Write-Host "Written: portal/.env" -ForegroundColor Green

# Also write portal/web/.env so Next.js picks up NEXT_PUBLIC_* vars during build
$webEnvPath = Join-Path $PSScriptRoot '..' 'portal' 'web' '.env'
$webEnvContent = @"
# Auto-generated by azd post-provision hook — $(Get-Date -Format 'yyyy-MM-dd HH:mm')
NEXT_PUBLIC_AZURE_TENANT_ID="$tenantId"
NEXT_PUBLIC_AZURE_CLIENT_ID="$clientId"
NEXT_PUBLIC_API_BASE_URL="/api"
"@
$webEnvContent | Set-Content $webEnvPath -Encoding utf8
Write-Host "Written: portal/web/.env" -ForegroundColor Green

# Also write portal/api/local.settings.json for local func development
$localSettingsPath = Join-Path $PSScriptRoot '..' 'portal' 'api' 'local.settings.json'
$localSettings = @{
    IsEncrypted = $false
    Values = @{
        AzureWebJobsStorage        = ''
        FUNCTIONS_WORKER_RUNTIME   = 'node'
        FUNCTIONS_EXTENSION_VERSION = '~4'
        AZURE_TENANT_ID            = $tenantId
        AZURE_CLIENT_ID            = $clientId
        AZURE_CLIENT_SECRET        = (Get-AzdEnv 'AZURE_CLIENT_SECRET')
    }
} | ConvertTo-Json -Depth 3
$localSettings | Set-Content $localSettingsPath -Encoding utf8
Write-Host "Written: portal/api/local.settings.json" -ForegroundColor Green

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

Write-Host "`n=== Post-provision complete ===" -ForegroundColor Cyan
Write-Host "Portal URL:    $swaUrl"
Write-Host "Function App:  $(Get-AzdEnv 'AZURE_FUNCTION_APP_URL')"
Write-Host "Key Vault:     $(Get-AzdEnv 'AZURE_KEY_VAULT_NAME')"
Write-Host ""
Write-Host "Local dev files written:" -ForegroundColor DarkGray
Write-Host "  portal/.env"
Write-Host "  portal/api/local.settings.json"
Write-Host ""
